# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 455f683dcd94064a2586e7640c4bc14d8e8b7f60814ede4feb060f79c8e050ca85df37cbe2a4337ec31c2b53150587381ed7a2aee410190d7a03caa027a41354

test:
  secret_key_base: fb475f280d894e65aef1256c016579c9652cd08d8afd8a967b0e148e16181711522ab7608c1ca12c4ae8c30e7a356dbef82ce1d2c28a46e6facfc4da3a5d4e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
